---
title: Neuromorphe Zwillinge, schmerzfreie Bewusstseinsmaschinen und andere Monster
subtitle: Der faustische Pakt der Neurowissenschaft mit der KI
author: Beat Bichsel
date: 2025-05-23
tags: [KI, Neurowissenschaft, Bewusstsein, Ethik]
lang: de
---

«Berner Forscher wollen einen Pakt mit der KI abschliessen» - der Titel eines Artikels in der Berner Tageszeitung *Der Bund* vom 11. März 2025 über ein Forschungsprojekt an der Uni Bern lässt aufhorchen. Was auf dem Spiel steht, wenn Forscher einen Pakt mit dem nicht hinlänglich Bekannten schliessen, sollte seit Goethes *Faust* dem kulturellen Gedächtnis zumindest der westlichen Hemisphäre nachhaltig eingeschrieben sein: Es ist nichts weniger als die Unschuld. Gretchen, das unschuldig-schuldige Opfer des Wissenschaftlers und Universalgelehrten Faust, kann davon ein Lied singen. Es ist ein Lied des Irrsinns, der Verrücktheit, der Ver-rückung: «Mein armer Kopf / Ist mir verrückt, / Mein armer Sinn / Ist mir zerstückt. / Meine Ruh' ist hin / Mein Herz ist schwer; / Ich finde sie nimmer / Und nimmermehr.»[^1]

[^1]: Johann Wolfgang Goethe: *Faust. Historisch-kritische Edition* \[= Goethe, Faust\], hrsg. von Anne Bohnenkamp, Silke Henke und Fotis Jannidis, Version 1.3 RC Frankfurt am Main / Weimar / Würzburg 2023, Faust. Eine Tragödie. Konstituierter Text. Bearbeitet von Gerrit Brüning und Dietmar Pravida, Verse 3382-3389, URL: http://v1-3.faustedition.net/print/faust.18#scene_1.1.15, abgerufen am 21.5.2025.

### Das verwegene Spiel um Macht, Big Tech und Menschenwürde

Oder ist Goethe einfach nur heillos antiquiert? Ich denke, so einfach sollte man es sich mit dem ollen Geheimrat aus Weimar nicht machen. Seine Charaktere im Faust-Drama haben es in sich: Mephistopheles, die Verkörperung des rational nicht Fassbaren, tritt im Gespann mit dem mit übermässiger technokratischer Neugier und Testosteron ausgestatteten Wissenschaftler und Verführer Heinrich Faust äusserst gewitzt, spassig und abgebrüht auf -- ein cooler Typ mit Pokerface. Und ganz und gar Manager, der weiss, was er dem Shareholder-Value und den Consumern schuldet. Er holt sich die Absolution für sein Tun bei der höchsten Instanz, dem «Herrn», dem er nach dem Abschluss der Wette um die Seele des Menschen attestiert: «Es ist gar hübsch von einem großen Herrn, / So menschlich mit dem Teufel selbst zu sprechen.»[^2] Recht subtile, subkutane Herrschaftskritik in einer Versuchsanordnung, in der Gut und Böse, Oben und Unten, fixierte Geschlechterstereotypen -- man denke an die «Walpurgisnacht» -- und radikale Versuche der Neuausrichtung des menschlichen Daseins sowie verlässliche Gewissheiten und kühne Illusionen durcheinanderwirbeln.

[^2]: Ebd., Verse 352-353, URL: http://v1-3.faustedition.net/print/faust.3, abgerufen am 21.5.2025.

Geraten beim Aufeinandertreffen der KI mit dem Menschen Vernunft und Sinne gleichermassen ausser Rand und Band wie in Goethes Drama? So viel scheint klar zu sein: Wenn von einem Pakt mit Künstlicher Intelligenz oder Maschinenbewusstsein die Rede ist, dürfen kritische Reflexion und das Aushandeln gesellschaftlich verbindlicher Regeln nicht aussen vor bleiben. Zu fragen ist, wer schliesst da mit wem nach was für Regeln was für einen Pakt? Und zu welchem Zweck? In diesem Blogpost wird die These vertreten, dass der Grat zwischen Gut und Böse, Nutzen und Schaden, innovativer Ingenieurskunst und verantwortungsloser Hybris in der KI-Forschung bisweilen schmal ist. Denn im kritischen Diskurs über die KI-Forschung stellen sich ebenso drängende wie bedrängende Fragen: Lassen sich künstlich erzeugte Intelligenz und das, was als Bewusstsein einer Maschine deklariert wird, überhaupt zum Wohle der Menschen nutzen? Bleiben Kritikfähigkeit, Gefühle und die Lust am Menschsein vollständig auf der Strecke, wenn wissenschaftlich-mathematisch imprägnierte Ingenieurskunst sich im Labor daran macht, menschliches Bewusstsein zu (re)konstruieren? Sind die ersten Schritte ins Verderben bereits getan und braust die digitale, neuromorph angereicherte Apokalypse unaufhaltsam auf uns zu? Zu vermuten ist: Es steht viel auf dem Spiel -- nicht zuletzt: Macht, Big Tech bzw. Big Business und die Menschenwürde. Und es fragt sich: Ist diesem abgründigen Spiel mit neurowissenschaftlicher Vernunft und Hightech-Forschung beizukommen oder doch eher mit literarisch-poetischer Vernunft und Phantasie?

### What Is It Like to Be a Machine?

Bewusstsein im KI-Kontext bedeutet mehr als nur intelligentes Verhalten. Es fragt sich, ob ein künstliches System subjektives Erleben haben kann, was in der Philosophie in der Regel als phänomenales Bewusstsein bezeichnet wird. Erschlossen wird das phänomenale Bewusstsein durch die Wie-ist-es-Frage: Wie ist es, etwas zu erleben? Wie ist es, ein Mensch, eine Fledermaus[^3] oder eben eine mit Bewusstsein ausgestattete Maschine zu sein? Beim Menschen tritt Bewusstsein ubiquitär auf und scheint universal zu sein. Es umfasst Empfindungen, Gefühle, Ich-Bewusstsein, Selbst-, Fremd- und Welt-Wahrnehmung und ist eingebettet in die Evolution des biologischen und des kulturellen Lebens auf dem Planeten Erde. Die Frage, ob Maschinen ein phänomenales Bewusstsein entwickeln können, entwickeln sollten oder möglicherweise ohne unsere direkte Einflussnahme entwickeln werden, sollte uns deshalb nicht nur im Rahmen der Illusionsfabrik Hollywood und ihren KI-Dystopien beschäftigen. Sie zielt ab auf die Fundamente des menschlichen Seins und dessen Verwurzelung im Universum. Unser Selbstverständnis, unser Verständnis von Materie und Geist und unsere ethischen Grundüberzeugungen werden durch die Begegnung mit Künstlicher Intelligenz bzw. dem Bewusstsein von Maschinen ebenso fundamental wie radikal herausgefordert.

[^3]: Vgl. dazu den Aufsatz von Thomas Nagel mit dem Titel *What Is It Like to Be a Bat?*, in: The Philosophical Review, Vol. 83, No. 4, (Oct., 1974), pp. 435-450 \[http://www.jstor.org/stable/2183914\]. Zur Diskussion der Thematik des phänomenalen Bewusstseins und der Qualia in der Philosophie vgl. insbesondere die Aufsätze von Peter Bieri, Frank Jackson, Joseph Levine, David J. Chalmers, Paul Churchland, Daniel Dennett und Sydney Shoemaker in: Thomas Metzinger (Hg.), *Grundkurs Philosophie des Geistes*, Bd. 1: *Phänomenales Bewusstsein*, Paderborn 2006, S. 33 -- 313.

Die Beschäftigung mit künstlicher Intelligenz und künstlichem Bewusstsein aus einer philosophisch motivierten kritischen Sicht auf die KI-Forschung ist insbesondere deshalb wichtig, weil theoretisches und praktisches, kulturelles und technisches Wissen zur Diskussion stehen und unser Handeln damit unmittelbar verknüpft ist. Denn die Art und Weise, wie wir über eine möglicherweise mit Bewusstsein ausgestattete Maschine nachdenken, beeinflusst nicht nur die Art und Weise, wie wir uns selbst, die Gesellschaft und das Menschsein wahrnehmen und verstehen, sondern auch die Rechte oder Pflichten, die wir Formen eines möglicherweise nichtmenschlichen Bewusstseins und dessen Trägern zuordnen.

### Die Spur der neuronalen Kernschmelze

Die im Fokus des *Bund*-Artikels stehende Studie wurde verfasst von Dr. Federico Benitez und Prof. Dr. Walter Senn, die beide im Rahmen der Computational Neuroscience Group am Institut für Physiologie an der Universität Bern forschen, sowie von Prof. Dr. Cyriel Pennartz, der die Abteilung für kognitive und systemische Neurowissenschaften an der Universität Amsterdam leitet. In ihrem Paper, das im Oktober 2024 in der Fachzeitschrift *AI and Ethics* unter dem Titel *„The conductor model of consciousness, our neuromorphic twins, and the human-AI deal"* publiziert wurde, versucht das Forschungsteam das Phänomen der künstlichen Intelligenz und des Maschinenbewusstseins aus neurowissenschaftlicher Perspektive neu zu denken.

Ziel der Forschungsgruppe ist es, konkrete funktionale Kriterien, an denen sich Bewusstsein festmachen lässt, in einem theoretischen Modell zu erfassen. Die Autoren vertreten eine grundlegend funktionalistische Position und damit die These, dass Formen künstlichen Bewusstseins prinzipiell möglich sind, sofern der Bauplan der Träger des Bewusstseins grundlegende funktionale Merkmale des menschlichen Gehirns erfüllen. Sie gehen damit von der Prämisse aus, dass man maschinelles Bewusstsein nach dem Vorbild des menschlichen Bewusstseins konstruieren kann. Ihr Argument aus neurowissenschaftlicher Sicht: Die Unterschiede zwischen einem biologischen und einem künstlichen Gehirn werden aufgrund der Fortschritte der KI-Forschung mit der Entwicklung einer -- zumindest in Ansätzen bereits existierenden -- neuromorphen Architektur zukünftiger Hardware überwunden.[^4] Das bedeutet: Insofern die KI-Systeme zunehmend neuronale Schaltkreise und Lernmechanismen nach Art eines menschlichen Gehirns aufweisen, nähern sich natürliche und künstliche Formen des Bewusstseins einander an. Die direkte Verbindung neuronaler Areale in einem biologischen Gehirn mit neuromorpher Hardware erweist sich in Experimenten offenbar bereits heute aufgrund neurophysiologisch konzipierter Technik als machbar. Benitez et al. (2024) jedenfalls sind zuversichtlich: In naher Zukunft werden Chips -- so ihre Prognose -- vollständig analog arbeiten und zahlreiche Forschungsarbeiten sind angeblich in der Pipeline, die zeigen, dass entsprechende Hardware in biologisches Gewebe implantiert werden kann.[^5]

[^4]: Vgl. Benitez, F., Pennartz, C. & Senn, W.: *The conductor model of consciousness, our neuromorphic twins, and the human-AI deal*, in: *AI Ethics* (2024). https://doi.org/10.1007/s43681-024-00580-w \[= Benitez et al. (2024)\], Kap. 2.2 *Architecture and the substrate problem*, S. 4f.: «Neuromorphic engineering aims to build hardware that mimics the brain to harness its extreme parallelism and asynchronous nature for power efficiency and computing speed. This multidisciplinary area of research takes direct inspiration from the structure and operations of the brain and its basic units, to develop new kinds of hardware. The implementation of neuromorphic computing on the hardware level can be realized by a wide diversity of substrates, such as transistors, memristors, spintronic memories, threshold switches, among others.»

[^5]: Ebd., S. 5: «Nowadays, neuromorphic chips are not fully analogue, but an increasing portion of their subcomponent are, and the aim of fully analogue chips seems attainable. Additionally, there is a line of research on implementing this hardware on flexible arrays and flexible chips that can be implanted within biological tissues and to be effectively scalable. On top of this, a lot of effort has been invested in emulating learning and memory using the plasticity of the synaptic weights between different neurons, emulating biological brains.»

Wie be(un)ruhigend: Einer neuronalen Kernschmelze steht aufgrund neuromorpher Substrate damit vermutlich wohl kaum mehr etwas im Wege.

### Der neuromorphe *enTwin*

Um ihre Überlegungen zu konkretisieren, schlagen Benitez et al. (2024) ein Gedankenexperiment vor. In diesem wird ein neuromorpher Zwilling, ein *co-evolving neuromorphic twin (enTwin)*, entworfen: Neuromorphe Chips, d. h. Hardware nach dem Vorbild neuronaler Schaltkreise, werden in das Gehirn eines Kleinkinds mit degenerativer Hirnerkrankung implantiert, um die ausgefallenen Areale des Gehirns zu ersetzen und sich gemeinsam mit dem Kind weiterzuentwickeln. Indem die Daten dieser Chips in den verschiedenen Hirnregionen gesammelt und miteinander kombiniert werden, entwickelt sich ein neuromorpher Zwilling, welcher die wesentlichen Prozesse des Gehirns -- und damit nach Ansicht der Autoren auch die dem Bewusstsein zugrunde liegenden phänomenalen Prozesse -- funktional abbildet. Die Chips interagieren mit den neuronalen Strukturen des menschlichen Hirns, wachsen funktional mit und übernehmen zunehmend die Aufgaben der beschädigten Areale, so das Konzept der Forscher. Das Ergebnis wäre ein hybrides Wesen aus Mensch und Technik, dessen künstliche Komponenten alle Funktionen mitentwickeln, die für Bewusstsein nötig sind.[^6] Das Ergebnis dieser Verschmelzung von Mensch und Maschine schildern die Autoren mit den folgenden Worten:

[^6]: Vgl. ebd., Kap. 1.1. *Functional correlates of cosciousness*, S. 2 f.

*The enTwin is fed by tactile and proprioceptive information at the extremities, and by an electrography of the speech muscles. To prospectively assist speech formation, it is also supplied by visual and auditory information through latest-generation smart glasses and active ear plugs. For motor and speech assistance it is coupled with muscle stimulation devices. The hypothetical chip is built on flexible neuromorphic arrays with learnable synaptic connectivity and a neuromorphic architecture \[...\]. Blood sugar is measured to modulate the energy supply of the chip, which itself is implemented using neuromorphic technology.*[^7]

[^7]: Ebd., Kap. 2.3 *A co-evolving neuromorphic twin*, S. 5.

Der Berner Forschergruppe geht es insbesondere darum, die neurowissenschaftlichen und ethischen Implikationen des Gedankenmodells zu erfassen und zu diskutieren. Auf die Problematik der transhumanistischen Vision, welche dieses Gedankenexperiment entfaltet, wird zurückzukommen sein.

### Das 'Bewusstsein' des neuromorphen 'Dirigenten'

In der Weiterführung ihres Gedankenmodells entwickeln Benitez et al. (2024) in ihrer Studie ein empirisch fundiertes Modell des Bewusstseins, das *Conductor Model of Consciousness (CMoC)*, welches die Funktionen des Bewusstseins aufgrund des aktuellen Stands des neurowissenschaftlichen Wissens erfasst. Detailliert beschrieben wird, welche Module und Prozesse im Gehirn zusammenspielen, damit phänomenales Bewusstsein entsteht. Die Kernidee ist eine Art 'Dirigent im Kopf': Ein *Conductor*-Netzwerk koordiniert als Meta-Instanz die Informationsflüsse zwischen den Unter-Netzwerken im künstlichen Gehirn, indem es wie der Dirigent eines Orchesters Einsätze gibt und damit das Zusammenspiel ermöglicht. Das Modell sieht die folgenden untergeordneten Netzwerke vor: Ein *Encoder*-Netzwerk (E) verarbeitet die Inhalte der von der Aussenwelt eingehenden sensorischen Signale. Ein *Generator*-Netzwerk (G) erzeugt sensorische Muster aus Daten, welche aus dem Innern des Systems stammen. Diese liegen ebenfalls in Form von funktionalen Aktivierungsmustern vor, bilden jedoch die neuronalen Prozesse derjenigen Regionen eines menschlichen Gehirns ab, in denen die Erinnerungen, inneren Vorstellungen und Wahrnehmungen (z. B. in Träumen) festgehalten werden. In der Studie wird argumentiert, dass es die Helmholtz-Architektur[^8] des CMoC ermöglicht, semantische Strukturen in sensorische Daten umzuwandeln, indem diese aus internen Repräsentationen rekonstruiert werden.[^9] Einem dritten Netzwerk, dem *Discriminator*, kommt die Funktion zu, in Bezug auf jeden Input zu entscheiden, ob er intern erzeugt wird oder von einem äusseren Reiz stammt. Der 'Dirigent' überwacht und trainiert diese Netzwerke: Er verbessert die Leistung von Encoder und Generator und hilft dem Discriminator-Netzwerk, Wirklichkeit und Einbildung immer zuverlässiger zu unterscheiden.[^10] Gemäss der Studie von Benitez et al. (2024) wird es damit einem System mit künstlich erzeugtem Bewusstsein ermöglich, in einem kreativen Prozess ein eigenes Selbst- und Welt-Modell aufzubauen: Es erkennt, was «Ich» und was «Umwelt» ist, was reale, aus der Aussenwelt stammende Reize sind und was vom eigenen 'Gehirn' selbst erzeugt wird. Nach Benitez et al. (2024) erweist sich das künstlich erzeugte phänomenale Bewusstsein als eine durch die Meta-Instanz des 'Dirigenten' vermittelte private Erfahrung, die sich aus der Funktionalität des CMoC ergibt. Der 'Dirigent' manifestiert sich als ein innerer Sinn, der von der Aussenwelt her nicht zugänglich ist:

[^8]: Das Modell referiert auf die Wahrnehmungspsychologie von Hermann von Helmholtz, dem Begründer der modernen Physiologie in der zweiten Hälfte des 19. Jahrhunderts. Helmholtz' Wahrnehmungsexperimente zeigen, dass die Wahrnehmung das Resultat einer aktiven, unbewusst ablaufenden Schlussfolgerung ist, die Voraussagen darüber beinhaltet, was voraussichtlich wahrgenommen wird. Das bedeutet, dass das Gehirn aus Sinnesreizen und Vorerfahrungen Hypothesen über die Welt bildet und so aktiv, auch wenn ihm dieser prädikative Akt nicht bewusst ist, vorhersagt, was wahrgenommen werden wird. Vgl. dazu Kap. 3.1. *The CMoC extends the Helmholtz view of perception by creative processing*, S. 7f.

[^9]: Ebd., S. 7: «Helmholtz machines are able to extract semantic structures in sensory data by trying to recreate sensory data from the internal representation.»

[^10]: Gemäss Benitez et al. (2024) erweitert damit das CMoC das Helmholtz-Modell technisch betrachtet um eine generative Adversarial Network (GAN) Architektur: «GANs have proven to be cornerstones of powerful network architectures for image recognition, language processing, and translations of image to language. Likely, generative networks are implicated in mental imagery, and discriminative networks must then exist that tell apart imagined sensory activity from externally induced sensory activity. These networks need to be trained, and it is reasonable to assume similar plasticity mechanisms being involved as in the technical version of GANs.» Ebd., Kap. 3. *The conductor model of consciousness (CMoC)*, S. 6.

*The conductor may manifest as a very private sense that represents a kind of sensory modality for the owner's inner world, be it the awareness of a stimulus, or the awareness of the self. The conductor-mediated inner sense only emerges and exists within this individual, is not accessible from the external world, and in fact disappears when seen from the external physical world.*[^11]

[^11]: Vgl. ebd., Kap. 3.3 *Consciousness as conductor-mediated private experience emerging from funcionallity*, S. 9.

Aus philosophischer Sicht erinnert die Meta-Instanz des Conductor an Modelle des Bewusstseins, die nach einem höherstufigen Beobachter-Prinzip organisiert sind und die geistige Instanz eines Homunculus vorsehen. Benitez et al. (2024) verwenden die Homunculus-Metapher bewusst in einer Abbildung,[^12] um zu veranschaulichen, dass im klassischen Verständnis Wahrnehmung so imaginiert wird. Ihr eigenes Modell postuliert jedoch ihrer Auffassung nach keinen mysteriösen Homunculus, sondern ein konkretes neuronales Netzwerk, in dem Informationen aufgrund elektrischer Impulse verarbeitet werden. Damit soll verhindert werden, dass Bewusstsein animistisch als diffuser „Geist" im System gedacht wird. Alles bleibt funktional im Rahmen eines mechanistischen Verständnisses verankert: Der 'Dirigent' ist kein kleines Geistwesen, sondern ein in ein neuromorphes System integriertes neurofunktionales Modul, dessen Aufgabe klar definiert ist: Signale werden erfasst und verteilt.

[^12]: Ebd., Kap. 3. *The conductor model of consciousness (CMoC)*, S. 6.

### Die sprachliche Gestalt der Dinge

Inwiefern es in diesem Zusammenhang sinnvoll ist, von einer 'privaten Erfahrung' und von einem 'inneren Sinn' zu sprechen, welche sich der Wahrnehmung aus einer Aussen- bzw. der Dritten-Person-Perspektive entziehen, ist aus einer sprachphilosophisch reflektierten Sicht allerdings anzuzweifeln. In seiner Gebrauchstheorie der Sprache betont der Philosoph Ludwig Wittgenstein, dass Worte für innere Erlebnisse wie «denken», «Schmerz» oder «bewusst sein» ihre Bedeutung aus ihrer Verwendung in der Alltagssprache, den 'Sprachspielen' des Alltags, beziehen. Die Autoren verwenden solche Begriffe für künstliches Bewusstsein, als wären sie eins-zu-eins aus dem Alltagsgebrauch der Sprache in das neurowissenschaftliche Sprachspiel übertragbar. Wittgenstein macht darauf aufmerksam, dass es im Feld der Sprache darum geht, die Übersicht zu behalten, die Zusammenhänge zu sehen und diese übersichtlich darzustellen.[^13] Spricht man dem Maschinenbewusstsein Privatheit zu, wird impliziert das, dass dieses Bewusstsein auch in einem sozialen Kontext steht, in dem sich Bedeutung und Bewusstsein beim Menschen erst formen kann. Zentral in der Argumentation von Wittgenstein ist der Gedanke, dass die Art und Weise, «wie wir die Dinge sehen», dadurch bestimmt wird, wie wir von den Dingen sprechen. Dieses Argument Wittgensteins spricht nicht dagegen, dass Wörter in unterschiedlichen Sprachspiele nicht unterschiedlich verwendet werden können. Wichtig ist jedoch, «dass man sich dessen bewusst ist und klar zwischen den zwei Verwendungsweisen unterscheidet».[^14] Denn sonst besteht die Gefahr, dass ein Sprachspiel zu Verwirrungen führt und wir zum Beispiel das Bewusstsein in Maschinen falsch einschätzen.

[^13]: Vgl. Ludwig Wittgenstein, *Philosophische Untersuchungen*, Frankfurt am Main 1977, S. 82 \[Nr. 122\]: «Es ist eine Hauptquelle unseres Unverständnisses, daß wir den Gebrauch unserer Wörter nicht *übersehen*. -- Unserer Grammatik fehlt es an Übersichtlichkeit. -- Die übersichtliche Darstellung vermittelt das Verständnis, welches eben darin besteht, daß wir die \>Zusammenhänge sehen\<. Daher die Wichtigkeit des Findens und des Erfindens von *Zwischengliedern*. Der Begriff der übersichtlichen Darstellung ist für uns von grundlegender Bedeutung. Er bezeichnet unsere Darstellungsform, die Art, wie wir die Dinge sehen. \[...\]»

[^14]: Hans-Johann Glock, *Philosophical Investigations section 128: Theses in Philosophy and Undogmatic Procedure*, in: Arrington/Glock (Hg.), *Wittgenstein's Philosophical Investigations,* London/New York 1991*.*

### Einsicht in den «Chinese Room» - eine Übersicht

Um festzustellen, ob ein künstlicher Agent wie der *enTwin* tatsächlich Bewusstsein aufweist, schlägt das Forscherteam das Konzept eines erweiterten Turingtests (eTT) vor. Im klassischen Turing-Test geht es allein um äußerlich nicht unterscheidbares Verhalten. Der erweiterte Test von Benitez et al. (2024) umfasst hingegen funktionale und neuronale Kriterien: Ein Agent gilt demnach nur dann als bewusst, wenn er sowohl menschliches Verhalten ununterscheidbar ausführt als auch über eine interne Architektur verfügt, die die funktionalen Korrelate des Bewusstseins gemäss dem CMoC mit seinem Encoder-, Generator-, Discriminator- und dem leitenden Conductor-Netzwerk aufweist.[^15] Man müsste also -- bildlich gesprochen -- die Blackbox des abgeschlossenen «Chinese Room» öffnen und nachschauen, ob in seinem Inneren die notwendigen neuronalen Bausteine vorhanden sind, mit denen sich der Bauplan eines Bewusstseins realisieren lässt -- unabhängig davon, ob es sich bei diesen Bausteinen um ein Medium handelt, das physikalischer oder biologischer Natur ist. Ein solcher eTT würde einer hypothetischen *enTwin*-KI attestieren, bewusst zu sein, wenn: (i) ihr Handeln für einen Beobachter nicht von dem eines Menschen zu unterscheiden ist und (ii) sie realiter eine neuromorphe Gehirnarchitektur gemäß dem CMoC aufweist.[^16]

[^15]: Benitez et al. (2024), Kap. 3.6 *An extended Turing Test (eTT) for consciousness including functional an neuronal correlates*, S. 12f.

[^16]: Vgl. ebd. S. 12: «\[A\]n enTwin would be conscious is not only that it would behave like a human, but that each of its microscopic components behaves in a manner equivalent to biological neurons and networks of neurons involved in cognitive processes.»

Aus funktionalistischer Sicht leuchtet dieses Argument der Berner Forscher ein. Doch hier droht ein Fehlschluss. Die Philosophen Maxwell Bennett und Peter Hacker machen geltend, dass es irreführend ist, psychologische Begriffe unvermittelt, im Sinne Wittgensteins ‚unzusammenhängend' und in ‚unübersichtlicher Darstellung', Teilen des Gehirns zuzuschreiben. Nicht das Gehirn oder ein Neuronenensemble ‚denkt' oder ‚erlebt', sondern die Person als Ganzes. Verwendet man Sprache anders, entsteht ein *mereologischer Fehlschluss*, eine Verwechslung von Teil und Ganzem, nicht nur wenn man sich auf Menschen oder Tiere, sondern auch wenn man sich auf einen *enTwin* bezieht.[^17]

[^17]: Vgl. Maxwell Bennett, Peter Hacker, *Philosophical foundations of neuroscience. The Introduction*, in: Bennett, M.; Dennett, D.; Hacker, P; Searle, J.: *Neuroscience and philosophy, Brain, Mind, and Language*, New York 2007, S. 3-48, hier: S. 22: «The neuroscientists' mistake of ascribing to the constituent parts of an animal attributes that logically apply only to the whole animal we shall call 'the mereological fallacy' in neuroscience. \[...\] Human beings, but not their brains, can be said to be thoughtful or to be thoughtless \[...\] can be said to see, hear, smell and taste things; people, but not their brains, can be said to make decisions or to be indecisive.

Vor diesem Hintergrund ist zu fragen: Wer hat im CMoC eigentlich das Bewusstsein? Die Autoren sprechen davon, dass der 'Dirigent' ein ‚funktionales Korrelat' des Bewusstseins bzw. der Aufmerksamkeit sei.[^18] Wie erwähnt, erweist sich im Verlauf der Argumentation spätestens in der Formulierung «*The conductor may manifest as a very private sense that represents a kind of sensory modality for the owner's inner world»* der 'Dirigent' allerdings als inneres Sinnesorgan, durch das der ‚Besitzer' dieses Organs Vorgänge in sich selbst spürt. Damit kehrt der Homunculus, den man eigentlich loswerden wollte, nicht nur sprachlich unvermittelt in das funktionalistische geprägte Sprachspiel zurück. Und es erscheint dann nichts als logisch zu sein, dass man sich dazu verpflichtet fühlt, mit ihm einen *Human-AI-Deal* abzuschliessen.

[^18]: Benitez et al (2024), Kap. 3.1. *The CMoC extends the Helmholtz view of perception by creative processing*, Fig. 4, S. 8.

### ‚Next Generation' -- das Paradies der Transhumanisten

Mit ihrem Gedankenexperiment eines *enTwin* und dem Dirigentenmodell des Bewusstseins versuchen Benitez et al. (2024) bestehender Kritik an neurowissenschaftlich fundierten Projekten zur Erzeugung von künstlichem Bewusstsein zu begegnen und diese neu zu bewerten.[^19] Ihr Denkansatz erscheint dabei allerdings nicht weniger verwegen zu sein als derjenige, der den bisherigen Grossprojekte im Forschungsbereich des künstlichen Bewusstseins zugrunde lag, dem *Blue Brain Project* von John Markram und dem Nachfolgeprojekt *Human Brain Project*. Diese wurden von der EU mit immensen Forschungsgeldern ausgestattet, haben ihre grossangelegten Ziele jedoch im Wesentlichen verfehlt.[^20] Zwar geht es den Berner Forschern nicht darum, das menschliche Gehirn in einer neurophysiologisch konzipierten digitalen Simulation vollständig nachzubauen, sondern vielmehr darum, den Bauplan des menschlichen Gehirns zu verstehen und diesen im Rahmen eines Modells zu überdenken. Ihre Vision ist allerdings ebenso spektakulär wie spekulativ:

[^19]: Ebd., Kap., 2.1 *Re-evaluating criticisms against artificial counsciousness*, S. 4.

[^20]: Vgl. dazu zum Beispiel die Dokumentation des Schweizer Fernsehens: [Umstrittenes virtuelles Gehirn - Das Human Brain Project geht zu Ende: Was bleibt? - Wissen - SRF](https://www.srf.ch/wissen/gesundheit/umstrittenes-virtuelles-gehirn-das-human-brain-project-geht-zu-ende-was-bleibt#:~:text=Das%20Projekt%20ist%20von%20Anfang,Zellen%20nachzubauen%2C%20schlicht%20f%C3%BCr%20unrealistisch.).

*Our brains and our consciousness are the result of millions of years of evolution---a complex process featuring a plenitude of feedback loops of interactions between our ancestors and their environment. Artificial agents do not undergo such processes, but nothing impedes us from designing these systems as if they were the result of evolution. We could create these systems as if they had an evolutionary history. This retroactively embedded history could in fact be our own history as a species that evolved consciousness, including the embodied traces of evolutionary processes---the kinds of limbs best adapted to bipedal locomotion, for example, or the "innate" sense of self or centralized "I".*[^21]

[^21]: Vgl. Benitez et al. (2024), Kap., 2.1 *Re-evaluating criticisms against artificial counsciousness*, S. 4.

Ihre Annahme, dass es in naher - oder ferner - Zukunft möglich sein wird, künstliche Agenten so zu ‚designen', als ob sie das Resultat der menschlichen Evolution wären, als ob ihr ‚Geist' und ihr ‚Körper' durch die Geschichte und die Mechanismen der natürlichen und der kulturellen Evolution («evolutionary pressures and feedback»[^22]) geformt würden und sich dadurch ein innerer Sinn für ein Selbst oder ein zentralisiertes Ich ausbildete, bedingt, dass neuromorphes Engineering weiterentwickelt und auch angewendet wird. Das Berner Forschungsteam gibt sich auch in diesem Punkt zuversichtlich:

[^22]: Ebd.

*The next generation of flexible carbon neuromorphic substrates could be moulded to emulate biological neurons to a degree that makes it very difficult to sustain any principled opposition to artificial neurons---or brains. In summary, recent techniques and developments have closed the door to most of the arguments against a principled impossibility of artificial consciousness.*[^23]

[^23]: Ebd., Kap. 2.2 *Architecture and the substrate problem*, S. 5.

Misstrauen sollte man meiner Meinung nach nicht nur dem hinreichend bekannten Narrativ, dass bereits die ‚nächste Generation' technischer Hilfsmittel den ultimativen Durchbruch auf dem Weg ins 'goldene Zeitalter' ebnen wird. Bedenklicher ist vielmehr, dass diese Euphorie dazu führen dürfte, dass Gedankenexperimente, sollten sie sich in einem nachfolgenden Projekt, einem Forschungsprojekt der *«next generation»*, umsetzten lassen, auch wirklich umgesetzt werden. Vermutlich zunächst in einem Hochsicherheitslabor zwar, aber eben letztlich doch in der wirklichsten aller Wirklichkeiten, in unserer Lebenswelt. Was das in Bezug auf das Konzept eines *enTwin* bedeutet, wird im Kontext einer medizinischen Massnahme vermutlich erwünscht sein. Wenn Mensch und Technik tatsächlich miteinander verschmelzen, eins werden, wird dadurch jedoch nicht nur eine ‚Türe geschlossen', die Zweifel an der ‚prinzipiellen Unmöglichkeit von künstlichem Bewusstsein' verstummen lässt. Tür und Tor werden vielmehr geöffnet zu einer neuen Religion. Und bedenkt man, was für einen Weg die Verantwortliche der Big Tech-Firmen, allen voran Elon Musk mit seinem Unternehmen *Neuralink*, in den letzten Jahren eingeschlagen haben, wird diese Religion die Ideologie des Transhumanismus sein.

### Der *Human-AI-Deal* im Licht des Neuronenfeuers künstlicher Augen

Das ist auch den Berner Forschenden bewusst: Ihr Modell des CMoC in der Perspektive eines *enTwin* systemimmanent konsequent weiterdenkend, schlagen sie deshalb einen *Human-AI-Deal* vor. Da sich aufgrund ihrer Annahmen -- und zu vermuten ist: aufgrund weiterer Generationen neuromorpher Architekturen -- , dereinst auch die Unterscheidung zwischen kognitiven und affektiven Schmerzimpulsen modellieren und ‚labeln' lassen, ist ihre Idee die folgende: Angesichts möglicher Rechte-Konflikte zwischen den Menschen und einer bewussten KI sollte das Bewusstsein der KI-Agenten so gestaltet werden, dass diese Agenten zwar wissen können, was es bedeutet, Schmerzen zu haben, also zu einer kognitiven Sicht auf den Schmerz fähig, d. h. sich der «sensory components of pain»[^24] bewusst sind. Dagegen sollten sie jedoch davon befreit werden, leidvolle Erfahrungen machen müssen. Der anscheinend clevere Deal: Im Gegenzug akzeptieren die KI-Systeme mit Maschinenbewusstsein, dass Menschen weiterhin Vorrang in rechtlicher und moralischer Hinsicht behalten. Die Autoren erachten diesen Vertrag als fair: Die KI kommt dadurch nicht zu Schaden, da, wie vorausgesetzt wird, niemand freiwillig leiden will.

[^24]: Vgl. ebd., Kap. 4.5 *Affective versus sensory components of pain: a physiological perspective*: «The structures responsible for processing the sensory aspects of pain include the somatosensory thalamus, primary and secondary somatosensory cortex, while the affective aspect is thought to be processed by the medial thalamus, amygdala, and anterior cingulate cortex. Based on this neuronal separability, one might argue that it would be ethical to modulate or even eliminate the specific neuronal circuits responsible for the affective component of pain in neuromorphic hardware.»

Notwendig ist die Differenzierung zwischen kognitiven und affektiven Formen des Schmerzes aus der Sicht der Forscher aus zwei Gründen: (i) damit Wesen mit künstlichem Bewusstsein sich in die Menschen, die eben auch affektiv leiden und Schmerz empfinden, hineinversetzen können, eine Haltung der Empathie einnehmen und sie dadurch verstehen lernen -- und (ii) damit Wesen mit künstlichem Bewusstsein erkennen können, dass die Empfindung des Leids einem Wesen ,ein gewisses Mass an innerer Würde' verleiht.[^25] Das Risiko, dass Systeme mit maschinellem Bewusstsein ausser Kontrolle geraten könnten, würde dadurch eingedämmt, folgern die Berner Forscher in ihrer Studie:

[^25]: Vgl. ebd., Kap. 4.4 *Must pain hurt? A philosophical perspective*, S. 16: «Pain is only one dimension of suffering, and the absence of suffering is but one dimension of well-being. But at the very least, the capability for pain and suffering opens the door for empathy, and for assigning some degree of intrinsic dignity to any being having these capabilities.»

*To tame the risk of AI growing out of control we suggested a human-AI deal, setting a primacy for humans on their essential rights, while in turn offering sentient agents to be relieved from affective chronic pain. \[...\] The human primacy aims at building an ethical barrier to protect the majority of humans being left out from benefits brought by AI, while an optional relief from negative affects for sentient agents is not expected to impede their successful integration into our physical and social world.*[^26]

[^26]: Ebd., Kap. 5, *Conclusions*, S,18.

Wie kann sich eine solche Überlegung der geballten Wucht eines explizit eingestandenen Human-Supremacy-Denkens entledigen, ohne dem Zynismus zu huldigen oder sich der Naivität schuldig zu machen? Die Autoren versuchen es mit dem Eingeständnis, dass künftige KI-Systeme diesen Pakt eventuell neu verhandeln oder gar ablehnen könnten:

*Of course, these future AI systems should be able to re-negotiate this deal, while humans are allowed to reconsider it if getting out of hand. In fact, since sentient agents do not exist yet, it is first us humans that must agree on a roadmap how to design them and organize our co-existence.*[^27]

[^27]: Ebd., Kap. 4.3 *Trading rights against affects: a possible human-AI deal*, S. 15.

Wenn man bedenkt, dass aufgrund ihrer Forschung die Berner Neurowissenschaftler zu Beginn ihres Aufsatzes dazu angetreten sind, vor der Gefahr der Vermenschlichung der KI zu warnen, und sich vorgenommen haben, Bewusstsein einem KI-System weder unreflektiert zuzuschrei­ben noch abzusprechen, [^28] sollte uns diese Schlussfolgerung, so vernünftig und dringlich sie auch ist, eher beunruhigen als beruhigen. Denn offenbar ist es tatsächlich eine Wohltat, dass die neurowissenschaftlich konzipierte Roadmap bisher noch nicht umgesetzt werden kann und ,wir Mensch' uns noch verständigen können und verständigen sollten. Doch auf was für eine 'Roadmap' sollten wir uns da verständigen? Halten wir das Steuer überhaupt noch in der Hand? Oder werden wir vom Lauf der Dinge, der sich womöglich bereits zu einer Sturzflut entwickelt hat, letztlich mitgerissen? Bleibt uns angesichts der uns schon jetzt mit dem Neuronenfeuer ihrer künstlichen Augen anstarrenden hybriden Faust-Figuren nur noch die Kapitulation vor einer andern Gestalt Goethes, dem «Zauberlehrling».

[^28]: Ebd., Kap. 1. *Introduction*, S. 2: «Prominent AI researchers are warning society about the existential risks that AI poses to humanity. The possibility of consciousness arising in AI is also well considered in this community, including the danger of over- or under-attributing it to AI.»

### Die Auf-klärung des Mephistopheles' -- eine Häresie

Der Naturforscher und Universalgelehrte Faust schliesst den Pakt, der Margarethe zu Gretchen macht, entmenschlicht und um ihren Verstand bringt, mit Mephistopheles, der ambivalenten, magischen Kraft der Innovation, der Ausrichtung auf die Zukunft, der Befreiung des Menschen von naturgegebener Begrenzung, die mit dem Versprechen auf ewige Jugend lockt. Schon allein diese Analogie heutiger transhumanistischer Fantasien mit einer Tragödie, die Goethe in einem über 30-jährigen Ringen mit dem Faust-Stoff vor über 200 Jahren geschaffen hat, sollte zu denken geben. Umso mehr der dramaturgische Kniff Goethes, diese mephistophelische Kraft -- maliziös augenzwinkernd -- mit einer paradoxal-grotesken Grundstruktur auszustatten: Sie ist jene Kraft, «\[d\]ie stets das Böse will und stets das Gute schafft.»[^29]

[^29]: Goethe: Faust, Vers 1336, URL: http://v1-3.faustedition.net/print/faust.6#scene_1.1.3, abgerufen am 21.5.2025.

Vor diesem Hintergrund wird ein Pakt, der mit einer KI abgeschlossen wird, in seiner Monstrosität erkennbar. Einen Pakt mit einer KI oder einem maschinellen Bewusstsein zu schliessen, ist nicht Bestandteil des Narrativs des Mephistopheles'. Seine mit einem teuflisch-warnenden Lachen vorgetragene, in paradox-grotesker Form auftretende Kritik bezeichnet vielmehr das Umstrittene, eine «Häresie», welche im Sinne des Soziologen Pierre Bourdieus der Doxa, dem unbefragt Übernommenen, dem im sprachlichen Diskurs nicht Überprüften, entgegentritt.[^30] Diese Häresie hat sich der Aufklärung, der Entlarvung, Dekodierung und Dekonstruktion eines wie auch immer gearteten falschen Bewusstseins verschrieben.

[^30]: Vgl. dazu Pierre Bourdieu, *Entwurf einer Theorie der Praxis auf der Grundlage der kabylischen Gesellschaft*, Frankfurt am Main 1973, S. 325; und ders., *Die feinen Unterschiede. Kritik der gesellschaftlichen Urteilskraft*, Frankfurt a. M. 1982, S. 668.

Zu oft führen im neurowissenschaftlichen Diskurs die anderen, die faustischen Ambitionen und Kräfte Regie: Ein ganz und gar menschliches Szenario spielt sich ab, eines, das von einer nur bedingt schicksalshaften Dramaturgie einer griechischen Tragödie gesteuert wird; ein heroisches Szenario, das in seiner Naivität indes äusserst tragisch anmutet: Angestrebt wird das anscheinend Gute, geschaffen aber das Böse -- oder zumindest das Monströse. Wir sollten uns deshalb tunlichst davor hüten, mit 'Zauberlehrlingen' und ihren Produkten Deals abschliessen zu wollen. Das sollten wir weder im Labor tun, der Welt des wirklich Kleinen, der feuernden Neuronen, noch im Showroom des in tragischer Hinsicht Grossen, der Welt der oft genug mit dem Feuer spielenden Repräsentanten von Politik und Big Business.

::: {.callout-tip title="Slides" collapse="true"}
<iframe src="/assets/files/KI-Deal_PPT.pdf" width="100%" height="600px" loading="lazy" allowfullscreen title="KI-Deal Presentation Slides" aria-label="KI-Deal presentation slides">

This browser does not support PDFs. Please download the PDF <a href="/assets/files/KI-Deal_PPT.pdf">download the PDF</a> to view it.

</iframe>
:::